---
# tasks file for project

- name: Ensure releases dir exists (deploy_source.yml)
  file: >
    path="{{ webroot }}/releases"
    state=directory

- name: Ensure project git cache exists (deploy_source.yml)
  file: >
    path="{{ webroot }}/releases/.git_cache"
    state=directory

- name: Fetch repo updates (deploy_source.yml)
  git: >
    repo="{{ nmdhosting['repository'] }}"
    dest="{{ webroot }}/releases/.git_cache"
    version="{{ nmdhosting['revision'] }}"
    accept_hostkey=yes
    ssh_opts="-o StrictHostKeyChecking=no"

- name: Get release timestamp (deploy_source.yml)
  command: date +%Y%m%d%H%M%S
  register: timestamp

- name: Name release directory (deploy_source.yml)
  command: echo "{{ timestamp.stdout }}"
  register: release_path

- name: Create release directory (deploy_source.yml)
  file: >
    state=directory
    recurse=yes
    path="{{ releases_dir }}/{{ release_path.stdout }}"

- name: Cop release (deploy_source.yml)
  command: "rsync -avz {{ git_cache_path }}/ {{ releases_dir }}/{{ release_path.stdout }}"

- name: Update app version (deploy_source.yml)
  file: >
    state=link
    dest="{{ webroot }}/current"
    src="releases/{{ release_path.stdout }}"
