---

- name: make sure '{webroot}/shared/s3archive.rb' doesnt exist (templating.yml)
  file: path="{{ webroot }}/shared/s3archive.rb" state=absent

- name: Push s3archive.sh (templating.yml)
  template: src=s3archive.sh.j2 dest="{{ webroot }}/shared/s3archive.sh" mode=0700 owner=root group=root

#Wordpress

- name: WP - Push wp-config.php (templating.yml)
  template: >
    src=wp-config.php.j2
    dest="{{ webroot }}/shared/wp-config.php"
    mode=0700
    owner="{{ nmdhosting['apache_owner'] }}"
    group="{{ nmdhosting['apache_group'] }}"
  when: site_type == 'wordpress'

- name: WP - Push permissions.sh (templating.yml)
  template: >
    src=permissions.sh.j2
    dest="{{ webroot }}/shared/permissions.sh"
    mode=0755
    owner="{{ nmdhosting['apache_owner'] }}"
    group="{{ nmdhosting['apache_group'] }}"
  when: site_type == 'wordpress'

#Drupal

- name: Drupal - Push d7.settings.php (templating.yml)
  template: >
    src=d7.settings.php.j2
    dest="{{ webroot }}/shared/settings.php"
    mode=0700
    owner="{{ nmdhosting['apache_owner'] }}"
    group="{{ nmdhosting['apache_group'] }}"
  when: site_type == 'drupal'

- name: Drupal - Push permissions.sh (templating.yml)
  template: >
    src=permissions.sh.j2
    dest="{{ webroot }}/shared/permissions.sh"
    mode=0755
    owner="{{ nmdhosting['apache_owner'] }}"
    group="{{ nmdhosting['apache_group'] }}"
  when: site_type == 'drupal'