---
# tasks file for update

#- name: S3 archive
#  shell: "{{ archive_cmd }}"
#  when: action == 'update'

- name: ensure user/pass are set
  command: "drush -p5.5 upwd --password='{{ nmdhosting['admin_password'] }}' {{ nmdhosting['admin_username'] }}"
  args:
    chdir: "{{ webroot }}/current/docroot"
  when: action == 'update' and site_type == 'drupal'

- name: Check if package.json exists
  stat: path="{{ webroot }}/current/docroot/package.json"
  register: package

- name: npm install
  command: "npm install --unsafe-perm"
  args:
    chdir: "{{ webroot }}/current/docroot"
  when: package.stat.exists and action == 'update'

- name: drush updb
  command: "drush -p5.5 updb -y"
  args:
    chdir: "{{ webroot }}/current/docroot"
  when: action == 'update' and site_type == 'drupal'

- name: run permissions.shj
  shell: "{{ webroot }}/shared/permissions.sh"

- name: drush cc all
  command: "drush -p5.5 cc all"
  args:
    chdir: "{{ webroot }}/current/docroot"
  when: action == 'update' and site_type == 'drupal'
